name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install QEMU and i686-elf-gcc
      run: |
        brew update
        brew install qemu
        brew tap homebrew/cross
        brew install i686-elf-gcc

    - name: Make Install (libcx)
      run: |
        cd libcx
        make install

    - name: Make Check (libcx)
      run: |
        cd libcx
        make check

