name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    env:
      PREFIX: ${{ github.workspace }}/opt/cross
      TARGET: i686-elf
      PATH: ${{ github.workspace }}/opt/cross/bin:${{ env.PATH }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update
        brew install gmp mpfr libmpc isl zlib qemu wget

    - name: Build binutils
      run: |
        mkdir -p $HOME/src
        cd $HOME/src
        wget https://ftp.gnu.org/gnu/binutils/binutils-2.40.tar.gz
        tar -xzf binutils-2.40.tar.gz
        mkdir build-binutils && cd build-binutils
        ../binutils-2.40/configure --target=$TARGET --prefix=$PREFIX --with-sysroot --disable-nls --disable-werror
        make -j$(sysctl -n hw.ncpu)
        make install

    - name: Build GCC
      run: |
        cd $HOME/src
        wget https://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.gz
        tar -xzf gcc-13.2.0.tar.gz
        cd gcc-13.2.0
        ./contrib/download_prerequisites
        cd ..
        mkdir -p build-gcc && cd build-gcc
        ../gcc-13.2.0/configure --target=$TARGET --prefix=$PREFIX --disable-nls --enable-languages=c --without-headers
        make -j$(sysctl -n hw.ncpu) all-gcc
        make install-gcc

    - name: Verify compiler
      run: |
        i686-elf-gcc --version

    - name: Build and install libcx
      run: |
        cd libcx
        make install
