name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          bison \
          flex \
          libgmp3-dev \
          libmpc-dev \
          libmpfr-dev \
          texinfo \
          wget

    - name: Build binutils
      run: |
        mkdir -p $HOME/opt/cross
        export PREFIX="$HOME/opt/cross"
        export TARGET=i686-elf
        export PATH="$PREFIX/bin:$PATH"

        mkdir -p $HOME/src
        cd $HOME/src

        wget https://ftp.gnu.org/gnu/binutils/binutils-2.40.tar.gz
        tar -xzf binutils-2.40.tar.gz

        mkdir -p build-binutils
        cd build-binutils

        ../binutils-2.40/configure --target=$TARGET --prefix="$PREFIX" --with-sysroot --disable-nls --disable-werror
        make
        make install

    - name: Build gcc
      run: |
        export PREFIX="$HOME/opt/cross"
        export TARGET=i686-elf
        export PATH="$PREFIX/bin:$PATH"
        cd $HOME/src

        wget https://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.gz
        tar -xzf gcc-13.2.0.tar.gz

        cd gcc-13.2.0
        ./contrib/download_prerequisites
        cd ..

        mkdir -p build-gcc
        cd build-gcc

        ../gcc-13.2.0/configure --target=$TARGET --prefix="$PREFIX" --disable-nls --enable-languages=c --without-headers
        make all-gcc
        make install-gcc

    - name: Verify i686-elf-gcc
      run: |
        export PATH="$HOME/opt/cross/bin:$PATH"
        i686-elf-gcc --version

    - name: Make Install (libcx)
      run: |
        export PATH="$HOME/opt/cross/bin:$PATH"
        cd libcx
        make install

    - name: Make Check (libcx)
      run: |
        export PATH="$HOME/opt/cross/bin:$PATH"
        cd libcx
        make check
