name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install QEMU
      run: |
        brew update
        brew install qemu

    - name: Install i686-elf-gcc manually
      run: |
        wget https://github.com/lordmilko/i686-elf-toolchain/releases/download/v1.0.0/i686-elf-macos.tar.gz
        tar -xzf i686-elf-macos.tar.gz
        sudo mv i686-elf /usr/local/i686-elf
        echo 'export PATH="/usr/local/i686-elf/bin:$PATH"' >> ~/.zprofile
        export PATH="/usr/local/i686-elf/bin:$PATH"
        i686-elf-gcc --version

    - name: Make Install (libcx)
      run: |
        cd libcx
        make install

    - name: Make Check (libcx)
      run: |
        cd libcx
        make check

